#!/usr/bin/env perl

# Copyright (c) 2025 André Kugland
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

use 5.036;
use strict;
use warnings;
use utf8;

use English              qw{ -no_match_vars };
use Encode               ();
use Getopt::Long::Parser ();
use List::Util           qw{ max };
use File::Basename       qw{ basename dirname };

use version 0.77 ();
our $VERSION = version->declare('v3.2.2');

my $help_message = <<~";;";
  rpl @{[ $VERSION->stringify() ]} - Rename files using Perl expressions

  Usage: rpl [OPTIONS] [FILES...]

    -e, --expr=EXPR         Perl expression to apply (can be used multiple times)
    -s, --script=FILE       Read Perl expressions from a file (- for stdin)
    -p, --prebaked=NAME     Use a prebaked expression (see --list-prebaked)
    -u, --util=NAME[,...]   Make a utility function visible to the expressions
                            (can be used multiple times; see --list-utils)
    -f, --from-file=FILE    Read list of files to rename from FILE (- for stdin)
    -d, --delim=CHAR        Set delimiter for --from-file (default: newline)
    -0, --null              Use NUL as delimiter for --from-file
    -c, --from-charset=ENC  Decode filenames from charset (e.g. latin1, utf-16le)
    -t, --to-charset=ENC    Encode filenames to charset (e.g. latin1, utf-16le)
    -b, --basename          Exclude directory part of the filename
    -x, --exclude-ext       Keep original file extension unchanged
    -o, --overwrite         Overwrite existing files
    -C, --check-collisions  Check for collisions (default is on)
    -a, --apply             Actually perform renames (default is dry-run)
    -m, --mkdirp            Create directories as needed
    -v, --verbose           Be more verbose (can be used multiple times)
    -q, --quiet             Be less verbose (can be used multiple times)
    -h, --help              Show this help message
    -V, --version           Show version information
    -l, --list-prebaked     List available prebaked expressions
        --list-utils        List available utility functions

  The boolean options, `--basename', `--exclude-ext', `--overwrite',
  `--check-collisions', `--apply', and `--mkdirp', can be negated by prefixing
  them with `no-' (e.g. `--no-apply', `--no-overwrite' etc).

  Examples:

    # Rename all files in the current directory to lowercase.
    \$ rpl -e 's/\\.txt\$/.md/' *.txt

    # Change the order of artist and song title in all mp3 files.
    \$ rpl -e 's/^(.+?) - (.+?)\\.mp3\$/\$2 - \$1.mp3/' *.mp3

    # Remove diacritics from all files in a directory.
    \$ find . -type f -print0 | rpl -0f- --prebaked=strip-diacritics

    All the above examples are dry-runs. To actually rename the files, add the
    `--apply' / `-a' option.
  ;;


# Render a die message as a user-facing error line. Strips Perl's
# ` at FILE line N.' suffix, which a die without a trailing newline picks up and
# which would otherwise leak the installed script path into ordinary output.
sub format_error {
  my ($msg) = @_;
  $msg =~ s{ \s+ \z }{}msx;
  $msg =~ s{ \s+ at \s+ \S+ \s+ line \s+ \d+ [.] \z }{}msx;
  $msg =~ s{ \s+ \z }{}msx;
  $msg =~ s{ \A . }{\L$&}msx;
  my $stop = $msg =~ m{ [.!?] \z }msx ? q{} : q{.}; # Don't double an existing full stop.
  return "Error: $msg$stop\n";
} ## end sub format_error


# Parse cli args and return a hashref of options.
sub params_get {
  my (@argv) = @_;

  my $params = {
    exprs            => [],                         # Perl expressions to be applied.
    utils            => [],                         # Utility functions visible to the expressions.
    files            => [],                         # Files to be renamed.
    from_charset     => undef,                      # Charset of the names in the files.
    to_charset       => undef,                      # Charset of the names to be written.
    basename         => 0,                          # Change the basename only?
    exclude_ext      => 0,                          # Exclude the extension?
    check_collisions => 1,                          # Check for collisions?
    apply            => 0,                          # Apply the changes?
    mkdirp           => 0,                          # Create directories as needed?
    overwrite        => 0,                          # Overwrite existing files?
    verbosity        => 1,                          # Verbosity level.
  };
  my $delim = "\n";

  # This block scopes the localized $SIG handlers below to argument parsing and
  # input validation, so every user-facing error raised here is reformatted
  # uniformly (with the `Try `rpl --help'' hint) and the handlers are restored
  # before the expressions are compiled.
  do {
    my $parser = Getopt::Long::Parser->new();
    $parser->configure(qw{ no_ignore_case bundling no_auto_abbrev });

    local $SIG{__DIE__} = sub {
      die format_error( $_[0] ) . "Try `rpl --help' for more information.\n";
    };
    local $SIG{__WARN__} = sub { die $_[0] };

    $parser->getoptionsfromarray( \@argv,
      'expr|e=s@'    => \$params->{exprs},
      'prebaked|p=s' => sub { push @{ $params->{exprs} }, prebaked_get( $_[1] ); },
      'script|s=s'   => sub { push @{ $params->{exprs} }, read_file( $_[1], undef ); },
      'util|u=s'     => sub {
        for my $name ( split m{ , }msx, $_[1] ) {
          utils_get($name);                         # Validate the name; dies if unknown.
          push @{ $params->{utils} }, $name;
        }
      },
      'from-file|f=s'       => sub { push @{ $params->{files} }, read_file( $_[1], $delim ); },
      'delim|d=s'           => \$delim,
      'null|0'              => sub { $delim = "\0"; },
      'from-charset|c=s'    => \$params->{from_charset},
      'to-charset|t=s'      => \$params->{to_charset},
      'basename|b!'         => \$params->{basename},
      'exclude-ext|x!'      => \$params->{exclude_ext},
      'check-collisions|C!' => \$params->{check_collisions},
      'apply|a!'            => \$params->{apply},
      'mkdirp|m!'           => \$params->{mkdirp},
      'overwrite|o!'        => \$params->{overwrite},
      'help|h'              => sub { say $help_message;                      exit 0; },
      'version|V'           => sub { say "rpl @{[ $VERSION->stringify() ]}"; exit 0; },
      'list-prebaked|l'     => sub { prebaked_list();                        exit 0; },
      'list-utils'          => sub { utils_list();                           exit 0; },
      'verbose|v+'          => sub { $params->{verbosity}++; },
      'quiet|q+'            => sub { $params->{verbosity}--; },
    );

    push @{ $params->{files} }, @argv;              # Remaining arguments are files.

    unless ( @{ $params->{exprs} } or $params->{from_charset} or $params->{to_charset} ) {
      die "no expressions provided\n";
    }

    my %seen = ();                                  # Deduplicate the list of files.
    $params->{files} = [ grep { !$seen{$_}++ } @{ $params->{files} } ];

    my %seen_util = ();                             # Deduplicate the list of utility functions.
    $params->{utils} = [ grep { !$seen_util{$_}++ } @{ $params->{utils} } ];

    die "no files provided\n" unless @{ $params->{files} };

    for my $opt (qw{ from_charset to_charset }) {
      # Load the charset codec.
      my $name  = $params->{$opt}              // 'utf-8';
      my $codec = Encode::find_encoding($name) // die "unknown charset: `$name'\n";
      $params->{$opt} = { name => $name, codec => $codec };
    } ## end for my $opt (qw{ from_charset to_charset })

    $params->{verbosity} = 0 if $params->{verbosity} < 0;  # Clamp verbosity to 0.
  };

  # Install the selected utility functions before compiling, so that they are
  # already declared when the expressions are compiled.
  utils_install( @{ $params->{utils} } );

  # Compile the expressions.
  $params->{exprs} = compile_exprs( @{ $params->{exprs} } );

  return $params;
} ## end sub params_get


# Read a file and return its content as an array of lines.
# Used by --script and --from-file options.
sub read_file {
  my ( $file, $delim ) = @_;
  die "Invalid delimiter: $delim\n" if defined $delim && length $delim != 1;
  local $INPUT_RECORD_SEPARATOR = $delim;
  open my $fh, '<', ( $file ne q{-} ? $file : '/dev/stdin' )
    or die "Can't open file $file: $OS_ERROR\n";
  my @lines = <$fh>;
  close $fh;
  if ( defined $delim ) {
    chomp @lines;
    @lines = grep { $_ ne q{} } @lines;
  }
  return @lines;
} ## end sub read_file


# The package the expressions are compiled into, and into which the selected
# utility functions are installed.
my $EVAL_PACKAGE = 'Isolated::Eval::Context';


# Compile expressions into anonymous subroutines.
sub compile_exprs {
  my (@exprs) = @_;
  my @result = ();
  state $utf8 = Encode::find_encoding('utf-8');
  for my $expr (@exprs) {
    $expr = $utf8->decode($expr) unless utf8::is_utf8($expr);
    my $code = <<~";;";
      package $EVAL_PACKAGE;
      sub {
        no strict; no warnings; use utf8;
        local \$_ = \$_[0];
        local \$SIG{__DIE__} = 'DEFAULT';
        local \$SIG{__WARN__} = 'DEFAULT';
      # line 1 __EXPR_FUNC__
        $expr
        ;return \$_;
      }
      ;;
    my $func = do {
      local $SIG{__DIE__} = 'DEFAULT';
      eval $code; ## no critic (ProhibitStringyEval, RequireCheckingReturnValueOfEval)
    } // do {
      my $err = $EVAL_ERROR;
      $err =~ s{ \Q at __EXPR_FUNC__ line \E \d+ .* }{}msx;
      die "Compilation failed for expr `$expr':\n$err\n";
    };
    push @result, { expr => $expr, func => $func };
  } ## end for my $expr (@exprs)
  return \@result;
} ## end sub compile_exprs


# Prebaked expressions.
my %PREBAKED_EXPRESSIONS = (
  'collapse-blanks' => [
    'Collapse consecutive blanks, trim leading/trailing blanks',
    's/ \A \s+ //msx',
    's/ \s+ \z //msx',
    's/ \s\s* / /gmsx',
  ],
  'normalize-nfc' => [
    'Normalize Unicode to canonical composition (NFC)',
    'BEGIN { require Unicode::Normalize }',
    '$_ = Unicode::Normalize::normalize( "C", $_ )',
  ],
  'normalize-nfd' => [
    'Normalize Unicode to canonical decomposition (NFD)',
    'BEGIN { require Unicode::Normalize }',
    '$_ = Unicode::Normalize::normalize( "D", $_ )',
  ],
  'normalize-nfkc' => [
    'Normalize Unicode to compatibility composition (NFKC)',
    'BEGIN { require Unicode::Normalize }',
    '$_ = Unicode::Normalize::normalize( "KC", $_ )',
  ],
  'normalize-nfkd' => [
    'Normalize Unicode to compatibility decomposition (NFKD)',
    'BEGIN { require Unicode::Normalize }',
    '$_ = Unicode::Normalize::normalize( "KD", $_ )',
  ],
  'strip-diacritics' => [
    'Remove diacritics from names',
    'BEGIN { require Unicode::Normalize }',
    '$_ = Unicode::Normalize::normalize( "D", $_ ); s/ \pM //gmsx',
  ],
  'trim' => [
    'Trim leading/trailing whitespace',
    's/ \A \s+ //msx',
    's/ \s+ \z //msx',
  ],
  'unidecode' => [
    'Convert Unicode characters to ASCII using Text::Unidecode',
    'BEGIN { require Text::Unidecode }',
    '$_ = Text::Unidecode::unidecode( $_ )',
  ],
  'windows-fullwidth' => [
    'Full-width replacements for chars forbidden in Windows',
    's{ ["*:<>?\x5c|] }{ chr( ord( $& ) + 0xfee0 ) }egmsx',
  ],
  'windows-fullwidth-rev' => [
    'Reverse full-width replacements for chars forbidden in Windows',
    's{ [＂＊：＜＞？＼｜] }{ chr( ord( $& ) - 0xfee0 ) }egmsx',
  ],
  'windows-fullwidth-with-slash' => [
    'Full-width replacements for chars forbidden in Windows and Unix (incl. /)',
    's{ ["*/:<>?\x5c|] }{ chr( ord( $& ) + 0xfee0 ) }egmsx',
  ],
  'windows-fullwidth-with-slash-rev' => [
    'Reverse full-width replacements for chars forbidden in Windows and Unix (incl. /)',
    's{ [＂＊／：＜＞？＼｜] }{ chr( ord( $& ) - 0xfee0 ) }egmsx',
  ],
);


# Get the expression with the given name.
sub prebaked_get {
  my ($name) = @_;
  die "Unknown prebaked expression: $name\n" unless exists $PREBAKED_EXPRESSIONS{$name};
  my ( $desc, @exprs ) = @{ $PREBAKED_EXPRESSIONS{$name} };
  return join q{; }, @exprs;
} ## end sub prebaked_get


# List all available prebaked expressions.
sub prebaked_list {
  binmode STDOUT, ':encoding(utf-8)';
  say q{The following prebaked expressions are available:};
  say q{};
  my $colwidth = max map { length $_ } keys %PREBAKED_EXPRESSIONS;
  for my $name ( sort keys %PREBAKED_EXPRESSIONS ) {
    my ( $desc, @exprs ) = @{ $PREBAKED_EXPRESSIONS{$name} };
    printf "  %s %s %s\n", $name,     q{ } x ( $colwidth - length $name ), $desc;
    printf "  %-*s  %s\n", $colwidth, q{},                                 $_ for (@exprs);
    say q{};
  } ## end for my $name ( sort keys...)
  return;
} ## end sub prebaked_list


# Symbol weights, heaviest first, with each subtractive pair sitting just above
# the symbol it is built from. Both directions walk this table in this order.
## no critic (ProhibitMagicNumbers) -- the numerals below are the domain's own values.
my @ROMAN_NUMERALS = (
  [ 1000, 'M' ], [ 900, 'CM' ], [ 500, 'D' ], [ 400, 'CD' ],
  [ 100,  'C' ], [ 90,  'XC' ], [ 50,  'L' ], [ 40,  'XL' ],
  [ 10,   'X' ], [ 9,   'IX' ], [ 5,   'V' ], [ 4,   'IV' ],
  [ 1,    'I' ],
);
## use critic


# The one spelling of each value that `to_roman' emits. Anchored and built from
# the subtractive pairs, so `IIII' and `IM' fail to match even though a lenient
# reader could assign them a value. Note that it also matches the empty string;
# `from_roman' rules that out separately.
my $CANONICAL_ROMAN = qr{
  \A M{0,3} (?: CM | CD | D?C{0,3} ) (?: XC | XL | L?X{0,3} ) (?: IX | IV | V?I{0,3} ) \z
}msx;


# Convert an integer in the range 1..3999 to a Roman numeral.
sub to_roman {
  ## no critic (ProhibitMagicNumbers) -- the bounds below are the domain's own values.
  my ($value) = @_;
  $value //= q{};
  die "to_roman: `$value' is not an integer between 1 and 3999\n"
    if $value !~ m{ \A \d+ \z }msx or $value < 1 or $value > 3999;
  my $roman = q{};
  for my $numeral (@ROMAN_NUMERALS) {
    my ( $weight, $symbol ) = @{$numeral};
    while ( $value >= $weight ) {
      $roman .= $symbol;
      $value -= $weight;
    }
  } ## end for my $numeral (@ROMAN_NUMERALS)
  return $roman;
} ## end sub to_roman


# Convert a Roman numeral in the range I..MMMCMXCIX to an integer. Case is
# ignored, but the spelling is not: only the canonical form `to_roman' produces
# is accepted, which makes the two exact inverses of each other.
sub from_roman {
  my ($value) = @_;
  $value //= q{};
  my $roman = uc $value;
  die "from_roman: `$value' is not a Roman numeral between I and MMMCMXCIX\n"
    if $roman eq q{} or $roman !~ $CANONICAL_ROMAN;
  my $total = 0;
  for my $numeral (@ROMAN_NUMERALS) {
    my ( $weight, $symbol ) = @{$numeral};
    while ( $roman =~ s{ \A \Q$symbol\E }{}msx ) {
      $total += $weight;
    }
  } ## end for my $numeral (@ROMAN_NUMERALS)
  return $total;
} ## end sub from_roman


# Utility functions, made visible to the expressions by --util.
my %UTIL_FUNCTIONS = (
  'to_roman' => {
    sig  => 'to_roman($n)',
    desc => 'Convert an integer between 1 and 3999 to a Roman numeral',
    func => \&to_roman,
  },
  'from_roman' => {
    sig  => 'from_roman($s)',
    desc => 'Convert a Roman numeral between I and MMMCMXCIX to an integer',
    func => \&from_roman,
  },
);


# Get the utility function with the given name.
sub utils_get {
  my ($name) = @_;
  die "Unknown utility function: $name" unless exists $UTIL_FUNCTIONS{$name};
  return $UTIL_FUNCTIONS{$name}{func};
}


# Install the named utility functions into the expression package. Functions
# that were not selected never enter it, so the namespace the expressions see
# stays limited to what was asked for.
sub utils_install {
  my (@names) = @_;
  no strict 'refs'; ## no critic (ProhibitNoStrict)
  for my $name (@names) {
    *{"${EVAL_PACKAGE}::$name"} = utils_get($name);
  }
  return;
} ## end sub utils_install


# List all available utility functions.
sub utils_list {
  binmode STDOUT, ':encoding(utf-8)';
  say q{The following utility functions are available:};
  say q{};
  my $colwidth = max map { length $UTIL_FUNCTIONS{$_}{sig} } keys %UTIL_FUNCTIONS;
  for my $name ( sort keys %UTIL_FUNCTIONS ) {
    my ( $sig, $desc ) = @{ $UTIL_FUNCTIONS{$name} }{qw{ sig desc }};
    printf "  %s %s %s\n", $sig, q{ } x ( $colwidth - length $sig ), $desc;
  }
  say q{};
  return;
} ## end sub utils_list


# Transform filenames using the provided expressions.
sub transform_names {
  my ($params)  = @_;
  my $old_names = $params->{files};
  my $new_names = [ map { transform_name( $params, $_ ) } @{$old_names} ];
  check_hard_collisions( $old_names, $new_names ) if $params->{check_collisions};
  return dodge_soft_collisions( $old_names, $new_names );
} ## end sub transform_names


# Run a step that may throw, dying with a contextual message on failure.
# The block performs its side effect (e.g. assigns to a captured variable);
# its return value is ignored, so falsy results are not mistaken for errors.
sub try_step {
  my ( $code, $errmsg ) = @_;
  my $ok = do {
    local $SIG{__DIE__} = 'DEFAULT';                # Wrap the raw failure, not a rendered one.
    eval { $code->(); 1 }; ## no critic (RequireCheckingReturnValueOfEval)
  };
  $ok or die "$errmsg: $EVAL_ERROR";
  return;
} ## end sub try_step


# Transform a filename using the provided expressions.
# Handles basename, extension, and character encoding based on parameters.
sub transform_name {
  my ( $params, $name ) = @_;

  # Split the filename into its components based on parameters
  my ( $dir, $subj, $ext ) = ( q{}, $name, q{} );

  # Handle basename - isolate directory if needed
  if ( $params->{basename} ) {
    ( $dir, $subj ) = $subj =~ m{ \A ( | .* / ) ( [^/]+ /? ) \z }msx
      or die "Failed to isolate basename from '$name'\n";
  }

  # Handle extension - isolate extension if needed
  if ( $params->{exclude_ext} ) {
    ( $subj, $ext ) = $subj =~ m{ \A
      ( .+? )
      ( /? | \.[[:alnum:]]+ (?: \.[gx]z | \.p?bz2 | \.lz(?:|[4o]|ma) | \.zstd? )? /? )
    \z }msx
      or die "Failed to isolate extension from '$subj'\n";
  } ## end if ( $params->{exclude_ext...})

  # Decode, transform, and re-encode the filename.
  try_step( sub { $subj = $params->{from_charset}{codec}->decode($subj) },
    "Failed to decode '$subj' from $params->{from_charset}{name}" );

  # Apply each expression in sequence.
  foreach my $expr ( @{ $params->{exprs} } ) {
    try_step( sub { $subj = $expr->{func}->($subj) },
      "Expression '$expr->{expr}' failed on '$subj'" );
  }

  # Re-encode to target charset.
  try_step( sub { $subj = $params->{to_charset}{codec}->encode($subj) },
    "Failed to encode '$subj' to $params->{to_charset}{name}" );

  return "$dir$subj$ext";
} ## end sub transform_name


# Check for hard collisions when renaming files.
sub check_hard_collisions {
  my ( $old_names, $new_names ) = @_;
  my $die = 0;
  my %map = ();
  for my $i ( 0 .. scalar @{$new_names} - 1 ) {
    my ( $old, $new ) = ( $old_names->[$i], $new_names->[$i] );
    $map{$new} //= [];
    push @{ $map{$new} }, $old;
  }
  for my $new ( sort keys %map ) {
    next if scalar @{ $map{$new} } == 1;
    my $old = $map{$new};
    say {*STDERR} "Multiple files will be renamed to `$new':";
    say {*STDERR} "  - `$_'" for @{$old};
    $die = 1;
  } ## end for my $new ( sort keys...)
  die "Aborting due to collisions.\n" if $die;
  return;
} ## end sub check_hard_collisions


# Avoid soft collisions when renaming file names.
#
# Returns fresh (old, new) lists plus a set of the temp names it introduced, so
# the caller can render those consistently. Does not mutate its arguments.
#
# Note: $tmpfunc is received as an argument for ease of testing. During normal
# operation, it should not be provided.
sub dodge_soft_collisions {
  my ( $old_names, $new_names, $tmpfunc ) = @_;
  $tmpfunc //= sub {
    my $tmp;
    do {
      my $rnd = join q{}, map { [ '0' .. '9', 'A' .. 'Z', 'a' .. 'z' ]->[ rand(62) ] } 1 .. 8;
      $tmp = "@{[ dirname($_[0]) ]}/@{[ basename($_[0]) =~ s/^(.{0,64}).*/$1/r ]}.$rnd.tmp";
    } while ( -e $tmp );
    return $tmp;
  }; ## end sub
  my @old          = @{$old_names};                 # Copies: leave the caller's lists untouched.
  my @new          = @{$new_names};
  my %seen         = ();
  my %is_temp      = ();                            # Temp names we introduce (for display decoding).
  my @appendix_old = ();
  my @appendix_new = ();
  for my $i ( 0 .. $#new ) {
    my ( $old, $new ) = ( $old[$i], $new[$i] );
    next if $old eq $new;
    $seen{$new} = $i;
    next if not exists $seen{$old};
    my $j   = $seen{$old};
    my $tmp = $tmpfunc->($old);
    $new[$j] = $tmp;
    $is_temp{$tmp} = 1;
    push @appendix_old, $tmp;
    push @appendix_new, $old;
  } ## end for my $i ( 0 .. $#new )
  push @old, @appendix_old;
  push @new, @appendix_new;
  return ( \@old, \@new, \%is_temp );
} ## end sub dodge_soft_collisions


# Create a directory and its parents as needed.
# This is a recursive function similar to 'mkdir -p' in Unix.
sub mkdirp {
  my ($dir) = @_;
  return if -d $dir;                                # Skip if directory already exists
  return if $dir eq q{/};                           # Handle root path edge case
  my $parent = dirname($dir);                       # Get parent directory
  mkdirp($parent) if not -d $parent;                # Create parent directory if it doesn't exist
  mkdir $dir or die "Can't create directory $dir: $OS_ERROR\n";
  -d $dir    or die "Directory $dir doesn't exist after creation attempt\n";
  return;
} ## end sub mkdirp


# Perform the actual file renaming operations.
sub perform_renames {
  my ( $params, $old_names, $new_names, $temp_names ) = @_;

  # Define whether we need to show character set information
  my $show_charset = $params->{from_charset}{name} ne $params->{to_charset}{name};

  for my $i ( 0 .. scalar @{$old_names} - 1 ) {
    my ( $old, $new ) = ( $old_names->[$i], $new_names->[$i] );
    next if $old eq $new;

    # Show progress information if verbosity allows
    if ( $params->{verbosity} > 0 ) {
      # Temp names we introduced are byte-derived from the source (from-charset)
      # names, so decode them with from-charset even though they occupy a target
      # slot; otherwise a charset conversion would mis-render them.
      my $new_charset = ( $temp_names && $temp_names->{$new} )
        ? $params->{from_charset}
        : $params->{to_charset};
      my $old_display = $params->{from_charset}{codec}->decode($old);
      my $new_display = $new_charset->{codec}->decode($new);

      if ($show_charset) {
        say "`$old_display' ($params->{from_charset}{name}) -> `$new_display' ($params->{to_charset}{name})";
      } else {
        say "`$old_display' -> `$new_display'";
      }
    } ## end if ( $params->{verbosity...})

    if ( $params->{apply} ) {
      # Create directory if needed
      my $new_dir = dirname($new);
      mkdirp($new_dir) if $params->{mkdirp} && $new_dir ne q{} && $new_dir ne q{.};

      # Check if source exists
      unless ( -e $old ) {
        die "Source file `$old' does not exist.\n";
      }

      # Check if target exists
      if ( -e $new ) {
        die "Target file `$new' already exists.\n" unless $params->{overwrite};
        unlink $new or die "Can't remove existing target `$new': $OS_ERROR\n";
      }

      # Perform the rename
      rename $old, $new or die "Can't rename `$old' to `$new': $OS_ERROR\n";
    } ## end if ( $params->{apply} )
  } ## end for my $i ( 0 .. scalar...)
  return;
} ## end sub perform_renames


# Main entry point. Returns the process exit code: 0 on success, 1 on failure.
# Errors are reported by die() throughout; catching them here keeps the exit
# code deliberate instead of letting die() leak whatever errno happens to be set.
sub main {
  binmode STDOUT, ':encoding(utf-8)';
  binmode STDERR, ':encoding(utf-8)';

  # Render every failure uniformly. Usage errors raised during argument parsing
  # install their own handler, which additionally points at `--help'; the hint
  # would only mislead for the runtime failures caught here.
  local $SIG{__DIE__} = sub { die format_error( $_[0] ) };

  my $ok = eval {
    my $params = params_get(@ARGV);
    my ( $old_names, $new_names, $temp_names ) = transform_names($params);
    perform_renames( $params, $old_names, $new_names, $temp_names );
    1;
  };
  return 0 if $ok;
  print {*STDERR} $EVAL_ERROR;
  return 1;
} ## end sub main


exit main() unless caller;                          # Run main() if the script is executed directly.


1;
