name: CI

on:
  push:
    branches: [ '*' ]

jobs:
  critic:
    name: "perlcritic"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v22

    - name: Run perlcritic
      run: nix develop -c perlcritic --brutal ./rpl ./rpl.t

  test:
    name: "prove"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v22

    - name: Run tests with prove
      run: nix develop -c prove ./rpl.t
